apiVersion: v1
kind: Service
metadata:
  name: web-app-k8n
  labels:
    app: web-app-k8n
  namespace: default
spec:
  selector:
    app: web-app-k8n
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-app-k8n
  namespace: default
  labels:
    app: web-app-k8n
spec:
  replicas: 4
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  selector:
    matchLabels:
      app: web-app-k8n
  template:
    metadata:
      labels:
        app: web-app-k8n
    spec:
      containers:
      - name: web-app-k8n
        image: udacity-capstone:latest
        imagePullPolicy: Always
        resources: {}
        ports:
        - containerPort: 8000
        env:
        - name: version
          value: v1
        readinessProbe:
          httpGet:
            path: /ready
            port: 8000
          initialDelaySeconds: 20
          timeoutSeconds: 1
          periodSeconds: 10
          failureThreshold: 3