apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-app
  labels:
    app: web-app
  namespace: default
spec:
  replicas: 3
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  selector:
    matchLabels:
      app: web-app
  template:
    metadata:
      labels:
        app: web-app
    spec:
      containers:
      - name: web-app
        image: 998598315760.dkr.ecr.us-west-2.amazonaws.com/udacity-capstone
        imagePullPolicy: Always #IfNotPresent
        ports:
        - containerPort: 80
        env:
        - name: version
          value: v2